# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e6493bc31d0621f4e85ac42c2252c0b1e8a31bf6131f3b120d7369b76244f930382b4657bc4d0fe6ad775a894c52517b4efb93a269cf22a131930782ef5be32

test:
  secret_key_base: 2da350f3f9065cf60de019baa5f4414d78f1478b964c8f8debf1851941d75042d3bac6d8e38d6c4b04c914f9a1201cdc6ae14feff56539fad297ac5168873568

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
